import React from 'react'
import { storiesOf } from '@storybook/react'

import {} from '@storybook/addon-info'
import { IconsFont, Stars } from '../src'

const stories = storiesOf('IconsFont', module)

// Add the `withKnobs` decorator to add knobs support to your stories.
// You can also configure `withKnobs` as a global decorator.
// stories.addDecorator(withKnobs);

// Knobs for React props
stories.add('IconsFont', () => {
	const options = [
		'flaticon-horizontal-arrows',
		'flaticon-baggage',
		'flaticon-take-off',
		'flaticon-transport-5',
		'flaticon-heart-1',
		'flaticon-heart-2',
		'flaticon-dustbin',
		'flaticon-arrows',
		'flaticon-heart',
		'flaticon-money-1',
		'flaticon-signs-1',
		'flaticon-skyscraper',
		'flaticon-suitcase',
		'flaticon-user-2',
		'flaticon-traveler-with-a-suitcase',
		'flaticon-man',
		'flaticon-travel-1',
		'flaticon-people-1',
		'flaticon-departure',
		'flaticon-people',
		'flaticon-stroller',
		'flaticon-interface-1',
		'flaticon-checked',
		'flaticon-close',
		'flaticon-arrows',
		'flaticon-dustbin',
		'flaticon-heart-2',
		'flaticon-heart-1',
		'flaticon-heart',
		'flaticon-shopping-cart',
		'flaticon-transfer',
		'flaticon-photo',
		'flaticon-credit-card-5',
		'flaticon-arrival',
		'flaticon-departures',
		'flaticon-social-media-6',
		'flaticon-social-media-4',
		'flaticon-youtube',
		'flaticon-social-media-3',
		'flaticon-social-media-2',
		'flaticon-social-media-1',
		'flaticon-social-media',
		'flaticon-commerce-1',
		'flaticon-money-2',
		'flaticon-coins',
		'flaticon-bed',
		'flaticon-calendar',
		'flaticon-calendar-1',
		'flaticon-money-1',
		'flaticon-signs-1',
		'flaticon-star-5',
		'flaticon-skyscraper',
		'flaticon-suitcase',
		'flaticon-building-2',
		'flaticon-user',
		'flaticon-technology-3',
		'flaticon-chat-3',
		'flaticon-menu-2',
		'flaticon-travel',
		'flaticon-calendar-1',
		'flaticon-gear',
		'flaticon-baby-cutlery-1',
		'flaticon-baby-cutlery',
		'flaticon-kitchen',
		'flaticon-calendar',
		'flaticon-transport-3',
		'flaticon-social-7',
		'flaticon-tag-3',
		'flaticon-star-3',
		'flaticon-placeholder-2',
		'flaticon-menu-1',
		'flaticon-settings-2',
		'flaticon-computer-2',
		'flaticon-transport-2',
		'flaticon-horizon',
		'flaticon-social-6',
		'flaticon-user-1',
		'flaticon-new',
		'flaticon-thermometer',
		'flaticon-snowflake-3',
		'flaticon-sun-2',
		'flaticon-half-moon',
		'flaticon-swimming-pool',
		'flaticon-beach',
		'flaticon-parking',
		'flaticon-knob',
		'flaticon-bell',
		'flaticon-croissant',
		'flaticon-serving-dish',
		'flaticon-tv',
		'flaticon-conditioning-air',
		'flaticon-dumbbell',
		'flaticon-pool',
		'flaticon-rest',
		'flaticon-wifi',
		'flaticon-interface',
		'flaticon-transport-1',
		'flaticon-nature',
		'flaticon-question-1',
		'flaticon-message',
		'flaticon-screen',
		'flaticon-favourite',
		'flaticon-hotel',
		'flaticon-filter',
		'flaticon-furniture',
		'flaticon-smart-tv',
		'flaticon-user',
		'flaticon-skiing-stickman',
		'flaticon-serving',
		'flaticon-flag',
		'flaticon-money',
		'flaticon-banner',
		'flaticon-gift-1',
		'flaticon-gift',
		'flaticon-medal',
		'flaticon-trophy',
		'flaticon-led-tv',
		'flaticon-social-4',
		'flaticon-social-3',
		'flaticon-question',
		'flaticon-building-1',
		'flaticon-building',
		'flaticon-cityscape',
		'flaticon-settings-1',
		'flaticon-social-2',
		'flaticon-symbol',
		'flaticon-signs',
		'flaticon-levels',
		'flaticon-communication-2',
		'flaticon-discount',
		'flaticon-snowflake-2',
		'flaticon-search-1',
		'flaticon-placeholder-1',
		'flaticon-briefcase',
		'flaticon-alarm-clock',
		'flaticon-alarm-1',
		'flaticon-alarm',
		'flaticon-technology-1',
		'flaticon-luggage',
		'flaticon-multimedia',
		'flaticon-cogwheel',
		'flaticon-mail',
		'flaticon-placeholder',
		'flaticon-sale',
		'flaticon-menu',
		'flaticon-moon',
		'flaticon-sun',
		'flaticon-search',
		'flaticon-agenda',
		'flaticon-tag',
		'flaticon-time',
		'flaticon-reception-bell',
		'flaticon-plane-ticket',
		'flaticon-disney',
		'flaticon-airplane-ticket',
		'flaticon-commerce',
		'flaticon-sports-car',
		'flaticon-snowflake-1',
		'flaticon-plate-of-food-with-rounded-cover-outline',
		'flaticon-magnifier-tool',
		'flaticon-moon-phase-outline',
		'flaticon-snowflake',
		'flaticon-shop',
		'flaticon-mercury-thermometer-and-a-snowflake',
		'flaticon-disneyland-castle',
		'flaticon-travel',
		'flaticon-transport-4',
		'flaticon-transport-3',
		'flaticon-transport-2',
		'flaticon-transport-1',
		'flaticon-transport',
		'flaticon-departure',
		'flaticon-departures',
		'flaticon-ticket-1',
		'flaticon-ticket',
		'flaticon-nurse',
		'flaticon-first-aid-case',
		'flaticon-car',
		'flaticon-coffee',
		'flaticon-moon'
	]
	options.sort()

	return (
		<ul>
			{options.map(icon => (
				<li>
					<IconsFont iconSize={20} color="black" icon={icon} />
					{`<IconsFont iconSize={20} icon={${icon}} />`}
				</li>
			))}
		</ul>
	)
})

stories.add('Stars', () => <Stars />)
